# Generated by Django 4.1.2 on 2022-10-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('nums_1', models.CharField(max_length=20)),
                ('nums_2', models.CharField(max_length=20)),
                ('nums_3', models.CharField(max_length=20)),
                ('nums_4', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=500)),
                ('innovation', models.CharField(max_length=500)),
                ('work', models.CharField(max_length=500)),
            ],
        ),
    ]
