# Generated by Django 4.1.2 on 2022-11-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('header', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='page1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='', null=True)),
                ('nums_1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nums_2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nums_3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nums_4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('service1', models.TextField(blank=True, default='', null=True)),
                ('service2', models.TextField(blank=True, default='', null=True)),
                ('service3', models.TextField(blank=True, default='', null=True)),
                ('innovation1', models.TextField(blank=True, default='', null=True)),
                ('innovation2', models.TextField(blank=True, default='', null=True)),
                ('innovation3', models.TextField(blank=True, default='', null=True)),
                ('work1', models.TextField(blank=True, default='', null=True)),
                ('work2', models.TextField(blank=True, default='', null=True)),
                ('work3', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
