# Generated by Django 4.1.2 on 2022-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page1',
            name='innovation',
        ),
        migrations.RemoveField(
            model_name='page1',
            name='service',
        ),
        migrations.RemoveField(
            model_name='page1',
            name='work',
        ),
        migrations.AddField(
            model_name='page1',
            name='innovation1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='innovation2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='innovation3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='service1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='service2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='service3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='work1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='work2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='page1',
            name='work3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='page1',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='page1',
            name='nums_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='page1',
            name='nums_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='page1',
            name='nums_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='page1',
            name='nums_4',
            field=models.CharField(default='', max_length=20),
        ),
    ]
