# Generated by Django 4.1.2 on 2022-11-01 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, default='', null=True)),
                ('progress', models.TextField(blank=True, default='', null=True)),
                ('nums_1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nums_2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nums_3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nums_4', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pm_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('header', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('introduction', models.TextField(blank=True, default='', null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about')),
            ],
        ),
    ]
