# Generated by Django 4.1.2 on 2022-10-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_page1_innovation_remove_page1_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page1',
            name='work3',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
